### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by victoroliveira** [nwutils/nw-angular-cli-example#1]
`Chrome 75.0.3770 (Windows 10.0.0) AppComponent should create the app FAILED
        TypeError: Cannot read property 'process' of undefined
        error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 33603585, rootNodeFlags: 33554433, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 49152, directChildFlags: 49152, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'app-root', attrs: [  ], template: null, componentProvider: Object({ nodeIndex: 1, parent: <circular reference: Object>, renderParent: <circular reference: Object>, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 49152, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, matchedQueries: Object, matchedQueryIds: 0, references: Object, ngContentIndex: -1, childCount: 0, bindings: Array, bindingFlags: 0, outputs: Array,  ...
            at <Jasmine>
            at new AppComponent (src/app/app.component.ts:13:44)
            at createClass (node_modules/@angular/core/fesm2015/core.js:24578:1)
            at createDirectiveInstance (node_modules/@angular/core/fesm2015/core.js:24400:1)
            at createViewNodes (node_modules/@angular/core/fesm2015/core.js:35006:1)
            at createRootView (node_modules/@angular/core/fesm2015/core.js:34878:1)
            at callWithDebugContext (node_modules/@angular/core/fesm2015/core.js:36407:1)
            at Object.debugCreateRootView [as createRootView] (node_modules/@angular/core/fesm2015/core.js:35644:1)
            at ComponentFactory_.create (node_modules/@angular/core/fesm2015/core.js:23542:1)
            at initComponent (node_modules/@angular/core/fesm2015/testing.js:3409:1)`

It is causing by window.nw calls. Do you have a estimation to fix it?

**Comment by victoroliveira** [comment]
I don't know if it's the best place but adding the code below on test.ts solves the problem

`global['nw'] = {
  process: {
    versions: {
      nw: '0.39.2',
      node: '12.3.1',
      chromium: '75.0.3770.90'
    }
  }
};`

**Comment by TheJaredWilcurt** [comment]
@victoroliveira I've implemented your fix into the repo. Can you figure out how to get E2E tests to pass?
